name: Deploy to Render

on:
    push:
      branches:
        - main

    # ---------------
    # MODIFICACIÓN 1: eliminar el trigger pull_request
    # ---------------

    # ---------------
    # MODIFICACIÓN 3
    # ---------------
    release:
      types: [created]
jobs:

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
